/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marissa Nur Aini
 */
public class Beratbadan extends javax.swing.JFrame {

    /**
     * Creates new form Beratbadan
     */
    public Beratbadan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Hitung = new javax.swing.JButton();
        cobalagi = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        knama = new javax.swing.JTextField();
        ideal = new javax.swing.JTextField();
        kberat = new javax.swing.JTextField();
        Laki = new javax.swing.JRadioButton();
        PR = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        Saran = new javax.swing.JTextField();
        Hasil = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ktinggi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(null);

        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        jPanel1.add(Hitung);
        Hitung.setBounds(90, 230, 80, 30);

        cobalagi.setText("Coba Lagi");
        cobalagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobalagiActionPerformed(evt);
            }
        });
        jPanel1.add(cobalagi);
        cobalagi.setBounds(210, 230, 90, 30);

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel1.add(keluar);
        keluar.setBounds(330, 230, 80, 30);
        jPanel1.add(knama);
        knama.setBounds(190, 60, 170, 30);

        ideal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idealActionPerformed(evt);
            }
        });
        jPanel1.add(ideal);
        ideal.setBounds(330, 270, 70, 30);
        jPanel1.add(kberat);
        kberat.setBounds(190, 140, 70, 30);

        Laki.setText("Laki - laki");
        jPanel1.add(Laki);
        Laki.setBounds(310, 180, 100, 23);

        PR.setText("Perempuan");
        PR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRActionPerformed(evt);
            }
        });
        jPanel1.add(PR);
        PR.setBounds(200, 180, 100, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("HASIL");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(180, 310, 160, 15);
        jPanel1.add(Saran);
        Saran.setBounds(80, 380, 340, 40);
        jPanel1.add(Hasil);
        Hasil.setBounds(80, 330, 340, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("CEK IDEAL TUBUH");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 20, 140, 30);

        ktinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ktinggiActionPerformed(evt);
            }
        });
        jPanel1.add(ktinggi);
        ktinggi.setBounds(190, 100, 70, 30);

        jLabel8.setText("Berat badan ideal anda adalah ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(110, 280, 200, 14);

        jLabel4.setText("kg");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(270, 140, 50, 20);

        jLabel9.setText("Tinggi");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(80, 110, 50, 14);

        jLabel10.setText("cm");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(270, 110, 50, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed

        if(knama.getText().equals ("") || kberat.getText().equals("") || ktinggi.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Data harap diisi");
        }else if (PR.isSelected() || Laki.isSelected()){
            try{
                Proses();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Inputan salah");
            }
        }else {
            JOptionPane.showMessageDialog(null, "Radio button harus dipilih");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_HitungActionPerformed

    private void cobalagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobalagiActionPerformed
        knama.setText("");
        ktinggi.setText("");
        kberat.setText("");
        buttonGroup1.clearSelection();
        ideal.setText("");
        Hasil.setText("");
        Saran.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_cobalagiActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed

        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    private void idealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idealActionPerformed

    private void PRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRActionPerformed

        PR.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_PRActionPerformed

    private void ktinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ktinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ktinggiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beratbadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beratbadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beratbadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beratbadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beratbadan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Hasil;
    private javax.swing.JButton Hitung;
    private javax.swing.JRadioButton Laki;
    private javax.swing.JRadioButton PR;
    private javax.swing.JTextField Saran;
    private javax.swing.JButton cobalagi;
    private javax.swing.JTextField ideal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kberat;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField knama;
    private javax.swing.JTextField ktinggi;
    // End of variables declaration//GEN-END:variables
}
